### ISSUE TITLE
documentation browser collapses-all after opening a file

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1126]
https://github.com/plugdata-team/plugdata/assets/86204514/a8434b75-ae6a-4e13-a9f2-ab109c871378

**Comment by timothyschoen** [comment]
This is kind of fixed, clicking patches will no longer collapse the whole panel.

However, docs browser is still terrible at handling changes in a folder, it will always collapse everything to make sure we don't show outdated info. This still happens when you save a patch that is in the docs browser, for example. That still needs to be fixed.

**Comment by tomara-x** [comment]
oh yeah! this is so good! thank you <3
