### ISSUE TITLE
numbers in comments are treated as numbers

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1185]
uncool

https://github.com/plugdata-team/plugdata/assets/86204514/f6b57be4-4699-467e-b57e-d50e99ec4c93

**Comment by caitp** [comment]
This seems to be caused by the atoms in the pd representation of the string being treated as floats (A_FLOAT), which causes atom_string() to format them using the %g printf specifier.

AFAIK, it should be okay for Comment to not use the text from the underlying pd object, or maybe not use an underlying pd object at all, since there are no outlets it seems like it shouldn't break anything. Am I wrong?

**Comment by timothyschoen** [comment]
I'm not sure if this is fixable: pd-vanilla also has this issue, but you need to save/reload the patch for it to happen. This is probably hard to get around from our side, since the problem is that pd indeed stores comments as a set of float/symbol atoms

**Comment by tomara-x** [comment]
ah i didn't try saving in vanilla
