### ISSUE TITLE
knob expands $0 in the inspector

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1188]
confusing, and a scary reminder of the old days when it was actually expanded and overwritten
 
https://github.com/plugdata-team/plugdata/assets/86204514/3193ae7a-5dda-4419-85d1-38298e7f10a0

**Comment by caitp** [comment]
looking into this a bit, the $0 is evaluated immediately during the loading of the patch via binbuf_evalfile -- so even though the $0 is stored in the file initially, it's completely absent from the representation within the pd patch, and presumably this affects any symbol which is stored with interpolated/evaluated variables. this is similar to that other issue with the message box drawing text from the Pd representation of the symbol, which has already been processed by atom_string(). -- otherwise, by the time knob_new() is invoked, symbols within its argv array have already been interpolated, and any $- and \- stuff has been handled and is lost.

I don't know if this would else/cyclone/etc (it probably would), but potentially pd could have a new token like "A_INTERSYMBOL" or something, which would be special cased by atom_getsymbolarg() which would evaluate the token at that point. Then, a message such as "knob" could be intercepted by plugdata and the editor value of the symbol token could be recorded.

or maybe I'm missing something and there's already a much easier way to do this.

**Comment by tomara-x** [comment]
umm.. you lost me lol
i think numboxes and other gui objects are doing it right, they display the literal $0, not the actual value

**Comment by caitp** [comment]
within the pd patch, as soon as the patch is loaded, the file text is tokenized (via atom_string), which evaluates or substitutes $- and \- automatically. The pd knob object itself never sees a hi_$0, only a hi_<substitution>.

We can have a separate string representation for the edited text in PlugData-land, but we can't retrieve that raw/unsubstituted text from the pd Patch/underlying knob object, because the pd object never sees the $0

**Comment by tomara-x** [comment]
aah! now i get what you mean! (i think)
but how come the other objects do keep their $0? if the whole patch gets parsed and the substitution happens before, shouldn't numboxes also lose their $0?

**Comment by timothyschoen** [comment]
Fixed with 5d1b1fd :)

**Comment by caitp** [comment]
> aah! now i get what you mean! (i think)
> but how come the other objects do keep their $0? if the whole patch gets parsed and the substitution happens before, shouldn't numboxes also lose their $0?

I think, some controls are intentionally hooking into controls from the editor canvas, which as I commented on discord, seems to use the source text.. there are probably a few other ways too

**Comment by timothyschoen** [comment]
Fixed, also for [function], [keyboard], [oscope~] and [pic] which had similar issues.
