### ISSUE TITLE
Resizing the standalone window is erratic

### ISSUE THREAD

**Issue by zkf** [plugdata-team/plugdata#122]
I guess the slowness could be caused by JUCE 6 and upgrading to 7 will fix that. But it seems like the size calculations may be skewed when resizing to the left or up?

https://user-images.githubusercontent.com/613216/169660214-9611f79b-da62-4dfc-ae98-27bff3af6116.mp4

**Comment by timothyschoen** [comment]
I think more people have complained about this for JUCE, especially when using a non-native titlebar. Resizing on Linux is a pain indeed! I'm running some tests with JUCE 7 now, I'll see if it's any better, but I'm afraid it won't be.

One improvement could be to use native window shadows instead of drawing them manually, but I've seen large inconsistencies between distros here (on my Arch build, there are no shadows at all!) which is why I enabled the custom shadows on Linux. It might have a negative impact on performance due to the transparency.

**Comment by timothyschoen** [comment]
Update: 

I think I know what causes this, so I've revived [one of those threads](https://forum.juce.com/t/juce-window-resizes-like-ass-on-ubuntu-x11/8759) to notify the JUCE devs. Unfortunately, they seem to be very busy since JUCE 7 was just released. I don't know enough about X11 to fix it myself, it would also require me to maintain my own JUCE fork, which I'm trying to avoid. I am a bit worried about our chances because this has been reported a bunch of times to no avail...

**Comment by timothyschoen** [comment]
I think this is better now on the develop branch. I'm reducing the rate of MouseEvent so that it doesn't trigger too many repaints, this makes it "smooth enough", it's not great but it's functional.

If this isn't fixed for you, let me know!
