### ISSUE TITLE
ZEXY lib can be inside the next version? 

### ISSUE THREAD

**Issue by meghadutam** [plugdata-team/plugdata#1224]
i liitle wish.

Thank you very much

**Comment by timothyschoen** [comment]
Hi!

There is currently no plan to add more object libraries to plugdata, since we'd also need to add new documentation (tooltips, etc) for those objects, make sure they work well in plugdata, maintain it in the future, etc, and we're currently in a stage of development where we're trying to work towards the first stable release.

 Sorry :(
