### ISSUE TITLE
[canvas.active] issues

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1226]
Problems with [canvas.active]:

- when the tab leaves focus: returns "0", expected behavior.
- when the tab is in focus: do nothing... Only return "1" when a click occurs on the canvas.
- when the object [canvas.active] is clicked: returns "0"... unexpected behavior.

tested under MacOs Sonoma 14.0 and Plug 0.8.0

**Comment by timothyschoen** [comment]
Should be fixed now!

It works similar to Pd, but there is one thing to keep in mind. This reports keyboard focus on a canvas: in Pd, keyboard focus and window activity are the same thing. In plugdata, there are more things in the window than just the canvas, so they are not the same thing. Clicking on the console or toolbar in plugdata will make canvas.active report 0, until you click on canvas again. This is kind of normal, since opening the console window in Pd will also make canvas.active report 0.
