### ISSUE TITLE
Arch compile problem

### ISSUE THREAD

**Issue by agraef** [plugdata-team/plugdata#1268]
For a while now (probably since the last gcc update) I've been getting this error while trying to build plugdata on Manjaro:

~~~
[  3%] Building C object Libraries/CMakeFiles/fluidlite.dir/FluidLite/src/fluid_init.c.o
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
cc1: note: unrecognized command-line option ‘-Wno-compound-token-split-by-macro’ may have been intended to silence earlier diagnostics
cc1: some warnings being treated as errors
make[2]: *** [Libraries/CMakeFiles/fluidlite.dir/build.make:76: Libraries/CMakeFiles/fluidlite.dir/FluidLite/src/fluid_init.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:823: Libraries/CMakeFiles/fluidlite.dir/all] Error 2
~~~

The fluid_init.c module being compiled there is literally empty, so this seems to be an issue with inconsistent options for the gcc command line being spit out by cmake.

I can't seem to get rid of this stupid (non-)error, no matter what I add to the cmake command line when configuring plugdata. Can anyone help?

**Comment by timothyschoen** [comment]
I believe @alcomposer also has this issue on Arch, so you're not alone.

Does 6b5e4fd8967d21197f41d233a115b5e596525bf4 help? If not, then we can remove the "-Wno-format" flag. I added this for the compilation of Pd's source code since it throws a lot of format warnings, but it seems to be the culprit here.
