### ISSUE TITLE
[vslider] and [hslider] coordinate change after saving

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1415]
- create a [hslider], save patch.
- move it with mouse (ex: x=100, y = 100)
- save patch : [hslider] move to x=103, y = 100

[vlslider] will move vertically

**Comment by timothyschoen** [comment]
Fixed!

**Comment by 60-hz** [comment]
Still happening on Nightly build: fa26fc8ad

**Comment by timothyschoen** [comment]
I'm still struggling a little bit. The problem is that the x/y coordinates of sliders are incorrect in pd-vanilla:

<img width="391" alt="Screenshot 2024-01-28 at 15 27 07" src="https://github.com/plugdata-team/plugdata/assets/44585538/8cd07f92-02c0-4cba-8899-e5197cdbfd6c">

I've just made more fixes.

So now I think I've found a good way to handle this: the inspector now shows the "correct" coordinates to prevent confusion. This means that if you enter "100, 100" as coordinates in plugdata, it will show the sliders with the same origin. But the real position saved to the save file is something like "102, 100" instead, so that it will actually appear the same in pd-vanilla.

So if you open an old patch that had (100, 100) as coordinates, that'll show differently now. However, if you save a new patch with (100, 100) coordinates it returns normally.
