### ISSUE TITLE
Bug: bang button colors don't update after switching themes

### ISSUE THREAD

**Issue by genericlastname** [plugdata-team/plugdata#1447]
Minor visual issue where other elements change colors after a new theme is selected but bang buttons retain the colors of the previous theme. See an example of placing a button down in the "classic" theme and then switching to the "max" theme.
![image](https://github.com/plugdata-team/plugdata/assets/7233887/2975ded7-cd30-4805-b7dc-fae7fc888b29)  

I am running plugdata 0.8.3 on Fedora Linux 39.

**Comment by timothyschoen** [comment]
Hi!

Unfortunately there is no way around this, since the bng colours are decided by the object properties, not by the theme.

Only thing you can do is hit the reset button at the top of the inspector to reset all properties to default. That will also reset the colour to the defaults for your current theme.

<img width="224" alt="Screenshot 2024-02-20 at 02 21 56" src="https://github.com/plugdata-team/plugdata/assets/44585538/a1f36daf-4036-40ea-ae86-b7a65e6991a9">
