### ISSUE TITLE
PlugData 0.9.0 nightly built, can't open [oscope~] from Show Object Browser

### ISSUE THREAD

**Issue by alexdrymonitis** [plugdata-team/plugdata#1533]
Trying to create an [oscope~] by clicking on its icon in the Show Object Browser, but PlugData can't create it.

**Comment by timothyschoen** [comment]
Hi!

[oscope~] has been renamed to [scope~]. The old [scope~] object that was a part of cyclone has been removed. This is a choice me and @porres made, because the objects were nearly identical.

In a recent update to the nightly build, I've also fixed all the old references to [oscope~] in the objects menu and browser, but maybe you don't have that one yet?

**Comment by alexdrymonitis** [comment]
You're right. I downloaded the latest nightly built and it's now working. The issue with [pdlua] crashing PlugData when I try to open its help patch has returned though... Should I open another issue?
