### ISSUE TITLE
PlugData should load font size according to the patch

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1663]
Pd patches have a font size saved to the file, but PlugData is unaware and it seems it uses a fixed font size... so if you have a patch saved with a big or small font, it all looks different in PlugData.

PlugData should be able to load the font size and also edit the patch with the same font size options for each patch, which requires a new configuration entry for each patch

<img width="510" alt="Screenshot 2024-06-24 at 17 55 23" src="https://github.com/plugdata-team/plugdata/assets/5360142/d18f4525-83c7-4210-9625-6a2b81926136">

this is related to https://github.com/plugdata-team/plugdata/issues/1657

**Comment by thumpclang** [comment]
This was discussed in #1402 as part of a series of changes to improve vanilla sizing compatibility. Currently in plugdata, object & comment font sizes are hardcoded to render at size 12 rather than other font sizes saved per-canvas in vanilla. I still agree that the ability to read/set/adjust canvas font size remains as one of the most important needs for vanilla compatibility, since it directly affects patch legibility for existing vanilla patches & documentation.

Related sidenote for @porres : you have opened several font-related issues on this board in the past 24 hours, some of which address overlapping/related subjects (for example #1657, as you mentioned). As a fellow user who in this case agrees with your opinion about font sizes, I find the fragmentation of this subject into multiple parallel issues to be quite difficult to parse, and it complicates the possibility of contributing to the conversation. I would respectfully suggest consolidating these related issues down to a single issue which encapsulates all related subject matter, for the sake of both the devs and also to enable other users to follow & contribute to the discussions.

**Comment by porres** [comment]
I can try and reorganize things, re edit them... I hadn't planned all of them beforehand... things kept popping up, and I do think anyway that being able to load the saved font sizes an isolated issue on its own that stands out as a bug as I see it

**Comment by porres** [comment]
closing in favor of https://github.com/plugdata-team/plugdata/issues/1882
