### ISSUE TITLE
control+c/control+v is inconsistent to ducplicate and could be reconsidered

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1664]
So, ctrl+d, as in Vanilla, duplicates things with an offset, but control+c/control+v pastes to the mouse position. This is inconsistent but I guess it could have been like that intentionally, anyway, if so, why exactly?

I don't know why it would make sense to have the distinct behaviour.

To get Vanilla as a Standard, the way it works is that it pastes elements to the exact same spot as the copied element, but it will paste with an x/y offset if the spot is taken. When you duplicate, either via ctrl+d or ctrl+c/v, the place is taken so the offset happens.

Copying and pasting to the exact same spot is a nice feature, as when copying a whole patch to another window. I needed that many times when working with help files. But we can't do this in PlugData, because the control+c/v operation is inconsistent and pasting to another windows chooses the mouse position as the reference point.

As for a feature on its own, I don't really like that idea. I get that you may want to choose exactly where to paste things and the way this is worked out in vanilla is that the pasted elements is selected, so you can click and drag around. I see the same happens in PlugData where one can just click on the selected items and move them around to better place them exactly where you want.

Maybe choosing the mouse position was considered a nice strategy but I am not sure it is the best option, as I think one just kinda guesses a more or so good place and then ends up readjusting anyway.

A better approach could be the same as used in Purr Data, where you paste the items to your mouse position but they are bound to the mouse cursor so you can still move around with the selection and find the actual optimal spot for you to then click and place things. I consider that idea better than what PlugData is trying to do.

And, well, in the same way, if one would duplicate something, the same thing should happen and the pasted elements would follow the mouse around until it'd get placed somewhere, and not behave in an inconsistent way.

As for pasting items to the exact same spot, I guess there could be a special paste operation for that, if possible, as an extra option.

**Comment by timothyschoen** [comment]
I think having different behaviour here makes a lot of sense, since it allows you to get both kinds of behaviour if you want. So it just makes copy/paste more flexible. If you want the object to be placed next to it (also with autopatching behaviour), use duplicate. If you want to place it anywhere else, move your mouse there and paste.

Another reason for this is that plugdata allows you to copy/paste pieces of patch from text, which pd-vanilla doesn't allow yet. If it would just spawn at the copy location with an offset, it has a very high likelihood of spawning somewhere you can't see it, so that makes it seem like paste didn't do anything.

**Comment by porres** [comment]
> If you want the object to be placed next to it (also with autopatching behaviour)

why would someone actually want the thing to be placed next to the original spot? this would force a displacement for sure. 

So I guess a consistent choice would be to be able to also make duplicate choose the mouse cursor position to duplicate items

as for 'autopatching behaviour', I don't understand, in neither case I can seem to paste elements and make any use of autopatching....

Well, people are accusing me of being too much of a Vanilla fanatic with stockolm syndrome, but my suggestion here was to follow how things work in Purr Data... and I actually proposed that to Vanilla sometime recently...

anyway, like I marked, this relates to https://github.com/plugdata-team/plugdata/issues/1665#issuecomment-2188288338 so if the approach there is to use the mouse cursor position, then it makes sense here to also follow suit...

**Comment by timothyschoen** [comment]
> why would someone actually want the thing to be placed next to the original spot? this would force a displacement for sure.

What I meant is, the standard behaviour for duplicate is already the same as pd-vanilla (thanks to your previous feedback on this, I think it's better now). Only difference is when you manually drag it to a different offset, then it will repeat the offset you dragged it to (which is the "autopatching" behaviour I meant, for lack of a better word). This makes it a lot faster to lay out grids of objects quickly, so I quite like that.

> anyway, like I marked, this relates to [#1665 (comment)](https://github.com/plugdata-team/plugdata/issues/1665#issuecomment-2188288338) so if the approach there is to use the mouse cursor position, then it makes sense here to also follow suit...

We already have copy/paste working the same as placing objects with keyboard shortcuts, i.e. it uses the mouse position at keyboard shortcut time. So it does follow suit! This is also comparable to purr-data, where duplicate doesn't attach to mouse, but copy/paste and object shortcuts do. The only difference here is that consistently, plugdata uses the mouse position when you click the shortcut, where purr-data attaches it to the mouse and requires a second click to place it.

> Well, people are accusing me of being too much of a Vanilla fanatic with stockolm syndrome

No worries, I'm not accusing you :) We just have a slightly different view on this. I prefer it if a keyboard shortcut instantly completes an action, so you can get back to normal patching immediately instead of requiring an extra step to complete. I realise some pd-vanilla users don't agree, and clearly personal preference plays a large role here. I think both ways can be valid.

If we try to be a bit more objective about it, we can compare it with how copy/paste generally works: if you copy a file or some text, the subsequent paste action is instant. It won't require another click to complete. Since this is such a common paradigm, it feels a bit off to me if it works differently (like in purr-data currently), since this is something that is ingrained though years of experiencing copy/paste this way.

**Comment by porres** [comment]
> So it does follow suit!

I know, I just mentioned it...

> This is also comparable to purr-data, where duplicate doesn't attach to mouse, but copy/paste and object shortcuts do.

Yeah, but I don't like that, and I think it's weird, meaningless, and inconsistent

I also see that selecting and pasting a single box autopatches them, which is clearly a flaw and a bug, for the record.

> I'm not accusing you :) 

I know you didn't :) 

> clearly personal preference plays a large role here.

of course

> I think both ways can be valid.

yeah, me too. Like I said in the other related issue, I guess I need to think more about this other approach.

> If we try to be a bit more objective about it, we can compare it with how copy/paste generally works: if you copy a file or some text, the subsequent paste action is instant. It won't require another click to complete. Since this is such a common paradigm, it feels a bit off to me if it works differently (like in purr-data currently), since this is something that is ingrained though years of experiencing copy/paste this way.

This reminds me of the discussion we had last week on Vanilla's repo, for reference:

https://github.com/pure-data/pure-data/issues/2351

In the discussion IOhannes mentioned that he thought no other program would paste to the current mouse position... and i mentioned Purr and PlugData (though we know both do it differently, and we also tend to agree both ways can be valid), and reading this thing back reminded me that MAX doesn't do that. It's just like in Pd! That is to say, there doesn't seem to be an "intuitive" aprroach!
