### ISSUE TITLE
inlets/outlets are not hidden in PlugData for iemguis and ELSE objects

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1900]
In Pd, GUIs hide the inlet/outlet when you have send/receive names.

Well, in the case of the atom boxes (number/symbol/list) the inlets/outlets aren't actually hidden, they do in fact disappear and are not present/functional anymore.

Now, in the case of iemguis they do in fact hide and keep functional, but in PlugData the inlets/outlets are always visible.

As for ELSE, my approach is different and it's actually the same as in MAX, where inlets/outlets are always hidden while in run mode. In edit mode they do hide as well if you have send/receive symbols.

Anyway, I hope you can make this consistent and compatible to Vanilla and ELSE.

**Comment by timothyschoen** [comment]
This is an intentional design choice: inlets/outlets hide when the object is not selected, but you can still use the inlet/outlet.

> but in PlugData the inlets/outlets are always visible.

Not true! Just deselect the object :)


This is the idea: pd-vanilla still allows connections to the object, even if iolets are hidden. For example, if you create a connection and then set the send symbol, the connection persists even though the outlet disappears. This means that if you do want to create that connection, you'd have to go through the steps of "connect-> set send symbol", and you can't do this the other way around. @alcomposer correctly noticed that this is a useless limitation, we can just allow connection creation anyway. I feel like this only has advantages, iolets are still hidden but you lose none of the functionality.

Regarding the different between iemguis and atoms: plugdata has made this consistent between all objects. They all hide their iolets, and they all still allow connections to be made nonetheless.

**Comment by porres** [comment]
> Not true! Just deselect the object :)

Well, I do select and unselect, and what I get is that when it is not selected, the inlets are grayed out, and when in edit mode it becomes blue, regardless if it is selected or not. And if you select you have a blue outline.

<img width="324" alt="Screenshot 2024-10-18 at 13 27 30" src="https://github.com/user-attachments/assets/4d43fd76-acc1-4f64-856d-057e3ab6ad51">
<img width="285" alt="Screenshot 2024-10-18 at 13 27 34" src="https://github.com/user-attachments/assets/2bbfa7d6-9b87-4df7-b45a-3b8b88e05055">

**Comment by porres** [comment]
> Not true! Just deselect the object :)

What I said is not actually true, and what happens is that we have the same bug that I pointed for [knob] in https://github.com/plugdata-team/plugdata/issues/901

The inlet/outlet keeps visible if you set the send/revceive name via messages. So it's actually consistent if you set this via the inspector. So I may need to reboot this issue.

**Comment by porres** [comment]
> This is the idea: pd-vanilla still allows connections to the object, even if iolets are hidden.

Sure, I know. 

>  @alcomposer correctly noticed that this is a useless limitation

where, in what context? I'm not sure what you mean.

> Regarding the different between iemguis and atoms: plugdata has made this consistent between all objects. They all hide their iolets, and they all still allow connections to be made nonetheless.

Geez, I didn't know about that, and now I see that atom boxes keep their inlet/outlet functional even though you have send/receive symbols.

I agree that it should be consistent and I wanna propose a PR to Vanilla that the inlet/outlet keeps functional and be consistent to iemguis... BUT....... while that doesn't happen, what you're doing is creating a patch incompatibility between plugdata and vanilla. Like, if someone makes a patch in Plugdata that uses the outlet even though there is a send symbol in an atom box, the patch simply breaks if used in Vanilla. And that breaks a golden rule for me.

Well, I guess I will break this issues into new different ones now

**Comment by porres** [comment]
> The inlet/outlet keeps visible if you set the send/revceive name via messages. So it's actually consistent if you set this via the inspector. So I may need to reboot this issue.
> 
> Edit: I mean this about iemguis.

Now I see that [function] for instance, has the same issue, so it is a general issue with iemguis and ELSE objects (not only [knob])
