### ISSUE TITLE
[netreceive] not working when not playing audio in DAW

### ISSUE THREAD

**Issue by rorxor** [plugdata-team/plugdata#197]
I am using the PlugData MIDI effect in Logic Pro X. 

I can send data to a PureData patch via [netsend], but cannot receive data within PlugData MIDI via [netreceive] unless it is sent using a [netsend] object within the same channel strip. Running two instances of PlugData MIDI in the same channel strip, I am able to send and receive data using [netsend] and [netreceive], but if I move one instance to another channel strip, they stop communicating.

Also, [bendout] doesn't seem to be sending anything to the software instrument.

**Comment by timothyschoen** [comment]
Hi! I responded on Facebook already but to make sure this information is available for everyone I'll answer here as well.

[bendout] was recently fixed, you can try a preview for the next version in the GitHub actions tab.

[netreceive] only works as long as the DAW is playing audio. More objects (like [metro]) suffer from the same issue. The reason is that Pd's run loop is attached to the DAW's audio callback. I'll see if I can make a specific solution for [netreceive]!

Cool that you're using the MIDI version, let me know if you find any other problems. Not that many people use the MIDI version (even though it's very cool imo), so it may have some more problems.

**Comment by timothyschoen** [comment]
I can't really solve this in a good way for now, but what helps, is that the DSP status button in the statusbar will now become orange when there is no audio being passed in, so you can use that of an indicator of whether or not netreceive is going to do anything.
