### ISSUE TITLE
Drifting DAW automation (Predelay)

### ISSUE THREAD

**Issue by Naskomusic** [plugdata-team/plugdata#1973]
Hey! Wanted to chime in and throw this one in the ring! 

When automating any created parameter in the daw using plugdata VST3 0.9.1 stable, the automation seems to be drifting forward in time. Seems it can have a predelay of up to 10ms, which would mean it's not caused by the 64sample buffer plugdata introduces (as its out of that range).

Windows 11 latest, Ableton live 11 running FLEX Asio at 512sample buffer.

![image](https://github.com/user-attachments/assets/05e17aee-e56b-4c2f-9c8a-966382c1adf4)

Cheers,
Nasko

**Comment by Naskomusic** [comment]
I have also observed some drifting with midi! 
It is within the 64smp buffer range plugdata comes with so i suppose this is intended behavior. I do wonder though why other plugins manage to be dead accurate with midi input.. 🫣

![image](https://github.com/user-attachments/assets/534a180e-5c81-4c15-87d5-189cee1e6a6a)

**Comment by timothyschoen** [comment]
> I have also observed some drifting with midi! It is within the 64smp buffer range plugdata comes with so i suppose this is intended behavior. I do wonder though why other plugins manage to be dead accurate with midi input.. 🫣
> 
> ![image](https://private-user-images.githubusercontent.com/89349046/389681717-534a180e-5c81-4c15-87d5-189cee1e6a6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTQ4ODYsIm5iZiI6MTczMzQ5NDU4NiwicGF0aCI6Ii84OTM0OTA0Ni8zODk2ODE3MTctNTM0YTE4MGUtNWM4MS00YzE1LTg3ZDUtMTg5Y2VlMWU2YTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE0MTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZDE1NTQxMGU1MmY3ZGQ5Nzk5MjIwODQ4MDU3MDg1MjQ5NmFlZDJiNzRkNTdmNjgxOWE4ZTM3Mjc2NGQzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GE4LnQm-52R1OVtIPmmiMycOCnG9reM0kEcMO7EDGag)

The reason we can't get this exactly right, is that pure-data objects all process 64 samples at a time. So that means we don't have a chance to "insert" MIDI in the middle of a block, so it will indeed by aligned to 64 samples :(

For automation, I think I've improved it a bit now! But what you're noticing for automation is a combination of 2 problems:
- Unlike MIDI, JUCE doesn't support sample-accurate automation. This is planned for JUCE 9. This means that automation can only be as accurate as the DAW's chosen block size. Many DAWs will dynamically make the block size smaller when automation is applied, to improve automation accuracy, so that helps a bit, but it depends on the DAW
- The same issue with MIDI input, we're also aligned to a 64 sample block.
- Combined, it means that the "best" accuracy we can get is 64 samples, but the worst accuracy you can get is determined by your DAW's block size, which is outside of our control until JUCE adds sample accurate automation.

**Comment by timothyschoen** [comment]
<img width="224" alt="Screenshot 2024-12-06 at 15 43 10" src="https://github.com/user-attachments/assets/6917098b-93a7-4a07-a83f-80340599b771">

A bit better! Bottom is the new version

**Comment by timothyschoen** [comment]
As you know, I've added an option to change the DSP block size, so you can now get 0-sample latency for MIDI.

Since JUCE doesn't support sample-accurate automation yet, I can't get that sample-accurate, but I have confirmed that it has the least amount of latency it could possibly have. Hope it helps!
