### ISSUE TITLE
Some issues / remarks on next PlugData

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#198]
Tried Plug data, build from GitHub's actions (Ccache fix #1316), OSX Monterey.

Again, congratulation for the work! Here are some remarks:

- [x] « pd shortcuts» for object, message, list and comment don’t work (Monterey, French keyboard), ui shortcuts works but have a weird characters.
- [x] Help tabs should be opened in Run mode to interact and read clearly before unlocking if needed (like pd vanilla).
- [x] console: error messages should be in red instead of orange, so they are more visible like vanilla pd.
error  « … couldn't create » -> should be in same line as original object name, or at least object name should be also red.
- [ ] symbol atom could have « symbol » as default name, to be less confused for newcomers (Vanilla removed the default name but I think it’s a big issue for learning).
- [ ] keymap under Edit have « Lock » but it don’t change « Temporary Lock » which stay the default CMD one.
- [ ] Canvas:  « in graph » property’s rectangle could be displayed a little bigger and appear a few pixel away from top left corner to be more convenient.
- [x] array gui update : create an array in a color theme, switch to the other theme, array don't refresh color untill click on it.
- [x] Is there any use for displaying the « properties » grayed option on every UI objects since the panel is toggling automatically, and the pin button is gone? ("Properties" is only useful on canvases now).
- [ ] Basic cursor change (edit mode / run mode, gui interaction) would be very convenient.
- [x] Multiple GUI resize at once would be very nice.
- [x] « ToFront » option on right clic is not available when multiple objects are selected.
- [x] box size consistencies: number2 and float box have 2 pixels height difference. Listatom and symbol atom are many pixels taller than number boxes, bang & toggle are even bigger. (Pure data just harmonized all boxes)
- [ ] « empty object »  should be renamed « New object » in add menu, to be consistent with « N » max shortcut.
- [x] zoom out could be centered from the current mouse position instead of left top corner.
- [x] When not in text field, Holding « Space » key could change the cursor to a « hand » and allow panning in the patch.
- [x] keyboard Command + K to connect 2 selected boxes  / auto patching would be very cool (new box while a previous one selected will connect it just below).

**Comment by timothyschoen** [comment]
Thanks! And a nice list of issues once again! The pd shortcuts not working is very strange, I'm not sure how that is possible, but I do really want to fix that one in particular.

Most of the other ones will be handled after the release, because there are so many crucial bug fixes in the current version already that I want to release it very soon. Otherwise I'll keep having to send people to get a GitHub actions build.

I do agree that all of these should be fixed, preferably before v0.6.3.

**Comment by 60-hz** [comment]
>Fortunately, you can remap them in the settings dialog.

I am using the Max shortcut that I found easier now!

>Most of the other ones will be handled after the release, because there are so many crucial bug fixes in the current version already that I want to release it very soon.

No worry, I will wait for support Gem / ofelia support so I can use it during workshop, so I guess keybord shortcut will be fixed before ;)

**Comment by timothyschoen** [comment]
I've fixed all the problem on this list that I agree with, there are a few left:

> « empty object » should be renamed « New object » in add menu, to be consistent with « N » max shortcut.

Since Max shortcuts are no longer the default, this isn't very important anymore, and I feel like "empty" more clearly describes what kind of object you are going to get than "new".

> Basic cursor change (edit mode / run mode, gui interaction) would be very convenient.
I prefer communicating this with colours and hover states, rather than with mouse cursors.

> keymap under Edit have « Lock » but it don’t change « Temporary Lock » which stay the default CMD one.
This will still get fixed someday, but I'll have to create my own system for this, since JUCE's way of handling keyboard shortcuts doesn't work when the shortcut is only a modifier key.

> symbol atom could have « symbol » as default name, to be less confused for newcomers (Vanilla removed the default name but I think it’s a big issue for learning).
Might still change this in the future, but since creating objects from typed name is kind of a secret feature, it's not that important yet. Also, I'm worried that calling it "symbol" might be polluting the namespace a bit?
