### ISSUE TITLE
Field width changes and doesn't expand

### ISSUE THREAD

**Issue by stillpointx** [plugdata-team/plugdata#254]
Field width changes and doesn't expand

![Field width](https://user-images.githubusercontent.com/28985314/205920671-6c6d6fc4-f473-4013-b553-c4dcdf4cea67.gif)

```
cat /etc/os-release 

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

cat /proc/version

Linux version 5.15.0-56-generic (buildd@lcy02-amd64-102) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022

```

**Comment by timothyschoen** [comment]
<img width="168" alt="Screenshot 2022-12-06 at 14 09 28" src="https://user-images.githubusercontent.com/44585538/205921344-28f4adfc-6b4f-4a78-96e4-3955d6901f35.png">

I believe the not-expanding part is normal for Pd, so the real problem here is that it shrinks when the text is short. Thanks for reporting!

**Comment by timothyschoen** [comment]
Fixed!
