### ISSUE TITLE
Key shorcut issues

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#338]
On macOS Monterey, french keyboard, key shortcuts for object, message, float or list boxes are broken, other have weird characters (long time issue).

Also, There is no way to delete point from [function], because Apple don't have the "delete" key, but use "backspace" instead.

<img width="199" alt="Capture d’écran 2023-01-08 à 23 29 56" src="https://user-images.githubusercontent.com/5449719/211222584-ed6cae68-c979-435e-a7c2-b1a58fcedb9b.png">

**Comment by timothyschoen** [comment]
@alcomposer fixed that problem with [function], you can now double-click the point to delete it. I think we might also want to put that into ELSE, since it's pretty useful. @porres, do you agree?

Other than that, yeah, those weird symbols need to go. I think that it's a "shift" icon, but it's not really selling that.

**Comment by 60-hz** [comment]
`Other than that, yeah, those weird symbols need to go. I think that it's a "shift" icon, but it's not really selling that.`

The problem is it cannot create object, message, float, list boxes or comment using any shortcut by default.
The one with weird shift are working.

**Comment by timothyschoen** [comment]
Oh yeah the AZERTY issue, I was aware of that. The problem is, there is no way in JUCE to detect keyboard layout, so I'll have to figure that out manually for each OS. I really need to do it, but it's gonna be very time-consuming.

**Comment by 60-hz** [comment]
Oh yes, I remember we already talked about it!
I updated my comment about the [function] weird behaviour.

**Comment by timothyschoen** [comment]
> But If I open the help file, the double click behaviour doesn't work anymore in any [function] object until I close help file... could be a bug?

It might be! @alcomposer do you happen to have time to look at this?

**Comment by claudionervi** [comment]
Hi Thimoty. I'm back to the problem with shortcuts in AZERTY. The ALT key is associated with "show overlays", I think that's not a good idea, since for all French-speaking countries, it's necessary to write the "~" of audio. I recommend changing the overlay shortcut for something else, for example ALT + another key, and freeing up Alt for its usual functions. In short, it's not a good idea to give a direct function to keys designed to be combined.
![azerty](https://github.com/plugdata-team/plugdata/assets/80156889/3ac464f0-d020-4896-b02a-f6e73b690017)
