### ISSUE TITLE
remove a few objects from the suggested list

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#360]
plugdata suggests not real objects but abstractions from ELSE that are used inside real abstraction externals. There could be a way to filter theses and only propose the real ones, maybe getting names from what really has a help file...

below only [multi.vsl] is a real object

![Screen Shot 2023-01-14 at 13 01 27](https://user-images.githubusercontent.com/5360142/212481806-95c60506-1f21-4863-a039-110b6d5ad95c.png)

**Comment by porres** [comment]
I am now taking care of the completion-plugin for vanilla, and it does a good job by checking just the help files

**Comment by porres** [comment]
I also now have a list of ELSE objects for a browse menu that I hope you can use for consistency, and it could also be a thing for you to use for suggestions

**Comment by timothyschoen** [comment]
Right now, plugdata just asks Pd for all objects that are available for creation, and it searches all search paths for abstraction. I think that's nicer than using helpfiles, in that case it would be hard to list objects like "midiin" because all midi objects use the same helpfile. I'm not sure how the completion-plugin solves that?

So I decided to just blacklist all objects that are built-in and not useful:

<img width="626" alt="Screenshot 2023-09-22 at 18 46 45" src="https://github.com/plugdata-team/plugdata/assets/44585538/ebbb428a-d511-489e-9f5b-a903bff22332">

I also blacklisted number~ because it's not very nice compared to numbox~

**Comment by porres** [comment]
> I'm not sure how the completion-plugin solves that?

it uses an internal list. I also have the object list in ELSE as part of a browser plugin, for vanilla and ELSE objects, you could use it

**Comment by porres** [comment]
I should remove number~ from cyclone, right?

**Comment by timothyschoen** [comment]
> I should remove number~ from cyclone, right?

I'm just hiding it from the list for now, for plugdata it's basically useless. Whether you remove it from cyclone is up to you, I guess numbox~ is almost always a better choice there too though.
