### ISSUE TITLE
range.hsl not working

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#371]
I think it's because of the canva.mouse object not actually being ported yet

**Comment by timothyschoen** [comment]
It has been ported! But I do see there's still some things wrong with it, and I'm also not sure how it behaves in graphs.

**Comment by timothyschoen** [comment]
Ah, there is a bigger problem here. Many objects like [canvas.mouse], [key], will not work inside abstractions in plugdata, because the GUI object that feeds it these events is not created. Planning to fix this in v0.7.1 because it's too big of a change to pull off right now.

**Comment by timothyschoen** [comment]
> Ah, there is a bigger problem here. Many objects like [canvas.mouse], [key], will not work inside abstractions in plugdata, because the GUI object that feeds it these events is not created. Planning to fix this in v0.7.1 because it's too big of a change to pull off right now.

We did luckily fix this issue. The only problem with range.hsl right now, is that in Pd, [canvas.mouse] will respond to mouse click before [hsl], but in plugdata this is reversed: the original object will receive earlier than a "listener".

So with this change, [range.hsl] works well in plugdata:

<img width="498" alt="Screenshot 2023-08-26 at 02 41 39" src="https://github.com/plugdata-team/plugdata/assets/44585538/a52810f1-5b95-47c1-bc33-47d679ec4164">

I've applied this fix to plugdata. I'll include this in the PR I'm gonna send you someday. I think it can't hurt anyway to ensure that the click is intercepted by [canvas.mouse] before [hsl] since the entire implementation depends on that.

**Comment by porres** [comment]
send me the PR soon please, but note ELSE doens't have gate ;) I'd use [router]!

**Comment by porres** [comment]
and how are you dealing with [note] in the compilation? I'd really like to get your help on this cause I don't wanna do something stupid and I think it also concerns plugdata, may I ask your attention to this too? I think you'll sort it in a minute... https://github.com/porres/pd-else/issues/1678

you can send me a PR for both
