### ISSUE TITLE
vanilla's comment shouldn't be created as an object

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#382]
currently [comment] creates vanilla's comment, which is not created as an object.

I can't create [comment] from cyclone also, by the way, because this one is loaded instead.

**Comment by timothyschoen** [comment]
This is by design. Cyclone/comment is only in plugdata to render cyclone help patches, it's not a fully usable object.

**Comment by porres** [comment]
What is not fully usable init? Is there a plan to fully port it? One way or another, Vanilla's comment should not be created as an object, and this would conflict anyway when comment is fully ported or any other external object named like it comes up... would you consider reopening this?

**Comment by timothyschoen** [comment]
Not really... Being able to create any Pd object by a text name is a part of how plugdata works. You can also type [msg] or [listbox] for example. It drastically simplifies the way object creation works, and the same system also causes [comment] to create a Pd comment. I think for most cases, this is actually a feature.

There is also no reason to replace the default Pd comment in plugdata, since we can write the implementation for comment ourselves. So we can already change the comment to be however we like it. Having extra comment objects in plugdata is kind of unnecessary, which is why I only support it for viewing help files. I might do a full implementation for [else/note] in the future though.

**Comment by porres** [comment]
I actually regret it that I used [comment] in the documentation of Cyclone. It got in the way for Purr Data / Pd-l2ork... it's nice you took care of it and I guess it's ok that you do not officially support it as an external (even thought it's there). I was just worried about compatibility, like if someone used cyclone's comment and it would call vanilla's comment in PlugData, but I see you took care of this by doing some magic.

> There is also no reason to replace the default Pd comment in plugdata, since we can write the implementation for comment ourselves. So we can already change the comment to be however we like it.

I don't get what you mean by this. if you say you wanna expand plugdata's comment to a fancier one, I would also get worried about compatibility to vanilla.

> I might do a full implementation for [else/note] in the future though.

that would be great :) I use it in some of my patches and would definitely like it to be in PlugData too
