### ISSUE TITLE
Discrepancy in handling of graph-on-parent abstractions

### ISSUE THREAD

**Issue by jamshark70** [plugdata-team/plugdata#411]
Just reporting for now... I'm not quite clear where to begin troubleshooting.

In [my abstraction pack](https://github.com/jamshark70/hjh-abs), I tried a couple of graph-on-parent abstractions with PlugData.

The simple one (monitor~) is fine. The more complicated one (fader~) barfs somewhere during initialization and doesn't make the controls available to the user.

![fader-failure](https://user-images.githubusercontent.com/318301/213847557-65b8a204-acff-4c02-8c39-c0bb002f789f.png)

A couple of possible issues:

- fader~ uses a symbol box; monitor~ does not.
- fader~ hides the object name and arguments.
- fader~ uses some dynamic patching, with the help of iemguts, during init.
  - Maybe iemguts is incompatible with PlugData.
  - Or maybe dynamic patching is problematic.

For my purpose, it's not extremely critical; fader~ is just part of a modular mixing board, but if you're running Pd in a DAW, then you have a mixer. But, it's odd, so I thought it would be worth reporting.

```
#N canvas 691 284 450 300 12;
#X declare -path hjh-abs;
#X obj 48 32 declare -path hjh-abs;
#X obj 48 72 monitor~;
#X obj 230 32 fader~ abc;
#A saved abc 7.62939e-06 0 main 0;
#X text 231 10 [fader~ abc];
```

**Comment by timothyschoen** [comment]
The first problem here that [fader~] will link to [else/fader~], which is why there is no gui at all in your screenshot. If you name the abstraction [fader2~] it will work, or you can create it with [hjh-abs/fader~] if the parent directory is in your search paths.

Then iemguts isn't included, but after installing it from the package manager, [fader~] loads correctly for me!

**Comment by jamshark70** [comment]
Ohhhhh ok... didn't think of namespace collision. Thanks for checking!
