### ISSUE TITLE
jumpy text when adding new object

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#433]
try typing "co" or "bli" in a new object

https://user-images.githubusercontent.com/86204514/214572118-6c901e43-9a17-48a7-b116-bb54320226b2.mp4

(btw it doesn't show the suggestion in the video because of my window capture, that's not a bug)

**Comment by timothyschoen** [comment]
Ohh that's a Linux exclusive! Probably because I switched to using my own custom UnicodeTextEditor. 

I now see that JUCE's fallback fonts system doesn't work at all on Linux, so I might as well write it so that it uses the regular TextEditor on Linux... The JUCE devs have told me before that they are working on a permanent solution, but it might take some time.

That is kind of bad news for you, no Arabic filenames/comments on Linux :(

On Linux:

<img width="201" alt="Screenshot 2023-01-25 at 14 18 22" src="https://user-images.githubusercontent.com/44585538/214573429-0d2b81d4-1da1-4759-a4dc-48c10083e106.png">

On macOS:

<img width="201" alt="Screenshot 2023-01-25 at 14 19 31" src="https://user-images.githubusercontent.com/44585538/214573671-49135a5a-7b7a-4e23-88d6-074320c8f395.png">

On Windows (but you have to pick a system font...):
<img width="201" alt="Screenshot 2023-01-25 at 14 23 27" src="https://user-images.githubusercontent.com/44585538/214574444-9bd23d3f-3eac-43e1-b305-a5ae3c9eb123.png">

**Comment by tomara-x** [comment]
nah that's not a problem for me. i did try having emoji in filenames and they do look like that. but it's good to know it's a linux exclusive :laughing: 
(close this? or..)

**Comment by timothyschoen** [comment]
No, I found out that I actually maybe can get fallback fonts to work on Linux!

But then I will still have to fix this bug

**Comment by alfonso73** [comment]
Hi, i have the same issue on Windows. Same issue happens not only in objects but in the parameters dialog or in the properties of sliders when setting i.e. send and receive symbols

**Comment by timothyschoen** [comment]
> Hi, i have the same issue on Windows. Same issue happens not only in objects but in the parameters dialog or in the properties of sliders when setting i.e. send and receive symbols

I found out that my fallback font system is actually only really working on macOS, because it draws text using the system API. 

I can basically revert all those changes, my new solution is to add symbols for Emojis and all non-dead languages to my own font. I still want to use Inter as the main font, but I will be merging it with [GoNotoCurrent](https://github.com/satbyy/go-noto-universal) and [Noto Emoji](https://fonts.google.com/noto/specimen/Noto+Emoji) to get a pretty complete unicode font.

That would fix all these bugs, and still provide good international support at the same time.

**Comment by tomara-x** [comment]
oh yeah!! i'm gonna annoy everyone! >:3
![Screenshot_2023-01-26_18-35-27](https://user-images.githubusercontent.com/86204514/214894078-34a27d64-a5d2-4ce0-931a-22393809e902.png)

**Comment by timothyschoen** [comment]
<img width="1046" alt="Screenshot 2023-01-26 at 17 39 45" src="https://user-images.githubusercontent.com/44585538/214895030-c5d52d29-42a0-483d-94e4-0da48b5a5c16.png">
