### ISSUE TITLE
object name suggestions (completion)

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#484]
This is a feature request instead of an issue:

Currently when I start typing an object name, the presented (completion) suggestions start with the characters that I type but don't show suggestions of objects with the typed characters further on in the name. In other words, it shows objects named "typedcharacters*" and not "* typedcharacters *"

Example: when I type "sf" I get "sfont~" as suggestion but don't get "readsf~" or "writesf~".

I think it would be very helpful if this would be the behavior.

**Comment by timothyschoen** [comment]
That can be done, I'll add it very soon!

**Comment by timothyschoen** [comment]
<img width="416" alt="Screenshot 2023-02-05 at 15 13 29" src="https://user-images.githubusercontent.com/44585538/216824574-9d42f853-6458-4f77-9634-269f6c96b06f.png">

I was using a very fast [Trie](https://en.wikipedia.org/wiki/Trie) lookup to make sure we can search through all the objects fast enough so the results are instant.

I've now added a second layer of searching that happens on its own thread, that will first search all the names, then the keywords, then object descriptions and finally inlet/outlet descriptions. It will continue searching until it has 20 results. These results will arrive a little bit later because searching like this isn't as efficient.

This update will be on the develop branch in a few minutes!

**Comment by sevdh** [comment]
That's is even more amazing!

Thanks a lot,

Edwin

**Comment by timothyschoen** [comment]
Done!

**Comment by sevdh** [comment]
Waiting for the compilation to be ready ;-)

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/actions/runs/4097174152 

That should be the one, there might still be some bugs in the completion, there are many more cases to consider when the suggestion doesn't always start with the typed text.

**Comment by sevdh** [comment]
It works!

I will play more with it and let you know my experiences.

I think this is very helpful if you don’t know the exact name or full name of an object.
