### ISSUE TITLE
[FR] resize group drag

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#511]
Currently there is individual origin group (multiple object) resize.

It would be useful to select multiple objects, and a resize area shows up around all objects, to allow group resize (all objects scale up from opposite side of selection region) See mockup below:
![resize group](https://user-images.githubusercontent.com/12004932/217711375-f52172f0-d220-4eec-b96c-6f96a48da11d.png)
@timothyschoen possibly we could achieve this very simply by allowing user interaction with the parent object in `faster-dragging` branch? This could also solve the issue in `faster-dragging` branch of selected objects popping forward, as there is also now a selection around all of them, it will be clearer to drag / resize / align etc. It makes sense for the object to pop forward if they are inside a selection box.

When we select multiple objects, I suggest that we use this all the time, as it's not clear currently which (or all) objects will try to align to other objects. This way we use the parent bounding rect of all the selected objects.

**Comment by alfonso73** [comment]
Would be great to get the same key modifiers for moving actions (SHIFT = 1 pixel move - CTRL/CMD = bigger grid moves)

**Comment by timothyschoen** [comment]
Unfortunately this concept is impossible to execute because of all the different resize rules there are for objects. For example, a keyboard, toggle, radio and text object would all resize a bit differently, so you can't keep everything proportionally correct when resizing a whole group. Objects would start overlapping and drifting, etc.
