### ISSUE TITLE
key - keyup

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#540]
Three issues with key and keyup:
1) They both always give values for capital letters (a-z) even when shift or caps-lock aren't pressed.
2) When switching to another tab and back to the tab with the key(up) objects they don't give output anymore until you click with the mouse in the corresponding window.
3) numbers keys on the numpad of an extended keyboard give huge numbers.

**Comment by timothyschoen** [comment]
The first two are fixed with f17b479ef10ff1b08b1a3a330312bfd461a57641. While I was looking at it, I also realised that it shouldn't output "Shift + space", but that it should give separate events for modifier keys, so that's also fixed now.

I haven't been able to test the third one yet because I have no number pad on my laptop, I'll test that one later. Thanks for reporting!

**Comment by sevdh** [comment]
Excellent!On 22 Feb 2023, at 17:54, Timothy Schoen ***@***.***> wrote:﻿
The first two are fixed with f17b479. While I was looking at it, I also realised that it shouldn't output "Shift + space", but that it should give separate events for modifier keys, so that's also fixed now.
I haven't been able to test the third one yet because I have no number pad on my laptop, I'll test that one later. Thanks for reporting!

**Comment by timothyschoen** [comment]
I've made some more improvements, number pad now works and I've verified that the output of these objects is the same as in Pd!
