### ISSUE TITLE
else/initmess weirdness

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#633]
The click function to [initmess] is not working, I wonder if other objects from ELSE with this functionality also don't work...

but weirdly enough, the list message is not reaching the list table for some crazy reason, see help file of display.

![Screen Shot 2023-03-03 at 14 07 30](https://user-images.githubusercontent.com/5360142/222784926-9593b31d-96d2-4890-b30a-13509962a0fe.png)

display didn't seem to be working on the help file of multi.vsl, but it looks fine here for some other crazy reason

**Comment by timothyschoen** [comment]
I searched for ```gensym("click")```, and found the following:

ELSE: lb, click, colors, initmess, lb, loadbanger, midi, openfile, rec
cyclone: capture, loadmess, coll, prob, seq, table

I've made sure the "click" message works on any object that appears as a text object. [else/click] also works now, but it needed a small change in ELSE:

Instead of doing ```canvas_vis(glist, 1)``` in click_click, we need:

```
        t_atom arg;
        SETFLOAT(&arg, 1);
        pd_typedmess(z, gensym("vis"), 1, &arg);
```

This makes sure that plugdata can intercept the vis message.

This will also work in pd-vanilla, so I suggest we change this in ELSE.

**Comment by porres** [comment]
> This will also work in pd-vanilla, so I suggest we change this in ELSE.

send me the PR? :)

**Comment by timothyschoen** [comment]
> > This will also work in pd-vanilla, so I suggest we change this in ELSE.
> 
> send me the PR? :)

Done!

**Comment by porres** [comment]
> I've made sure the "click" message works on any object that appears as a text object.

I can confirm with the current nightly build that else/click works and so does [imitmess], but I tried clicling in [sfont~] and [loadbanger] and it didn't work, so I'd ask you to check if all are really working

**Comment by porres** [comment]
gonna mention this in the actual issue
