### ISSUE TITLE
AudioUnit parameters show up as (DISABLED) paramxxx

### ISSUE THREAD

**Issue by t-scale** [plugdata-team/plugdata#796]
Tried with different hosts: Renoise, Reaper, MPC Software.
Parameters show up as (DISABLED) paramxxx.
<img width="624" alt="Screenshot 2023-04-07 at 15 20 08" src="https://user-images.githubusercontent.com/4723347/230615904-a034de88-895c-4e66-9adb-91f9ad00144c.png">

**Comment by tomara-x** [comment]
they show up like that in vst too, but they're changed when you add those parameters from the side bar, does that not work?
![Screenshot_2023-04-07_15-59-38](https://user-images.githubusercontent.com/86204514/230622234-0b97969f-eed9-46cd-946e-e88333d4ec4d.png)

**Comment by t-scale** [comment]
No, no matter what parameters I have in PlugData, they keep showing up as "(DISABLED)".
It's only happening with AudioUnits btw.
VST3 is fine:
<img width="623" alt="Screenshot 2023-04-08 at 17 58 01" src="https://user-images.githubusercontent.com/4723347/230730961-bea732ff-c0f2-4ba6-9047-b584a197373e.png">

**Comment by timothyschoen** [comment]
> No, no matter what parameters I have in PlugData, they keep showing up as "(DISABLED)". It's only happening with AudioUnits btw. VST3 is fine: <img alt="Screenshot 2023-04-08 at 17 58 01" width="623" src="https://user-images.githubusercontent.com/4723347/230730961-bea732ff-c0f2-4ba6-9047-b584a197373e.png">

Unfortunately this is a DAW issue, Logic/Garageband does support changing parameter names for Audio Units, but unfortunately some other DAWs apparently don't. The problem is also that many DAWs sort the parameters alphabetically, so having them start with (DISABLED) at least makes sure that the enable parameters will all be next to eachother, either at the start or end of the list.

So unfortunately, I can't solve this. I would recommend using the VST3 or LV2 versions if you're not using Logic or Garageband.
