### ISSUE TITLE
Sidebar representation of [param] not persistent between saves/opens

### ISSUE THREAD

**Issue by madskjeldgaard** [plugdata-team/plugdata#819]
Hi!

The sidebar representation of a `[param]` object does not seem to be persist between saves/reopens. If I make a patch, add a param using the sidebar, insert the object into my patch, save it, and then reopen it, the slider in the sidebar is gone, but the object is still inside the patch.

This tested on today's nightly and 0.7 both inside of Ableton as a VST and as a standalone.

Thanks

**Comment by timothyschoen** [comment]
Hi, this is now really a bug, more a side-effect of how parameters work. Parameters are not stored in the patch itself, they are stored in the DAW save. Since v0.8.0, there is now an option to "export workspace", which creates a special save file that also contains the parameters. Hope that helps!

Maybe someday I'll work on a better system to store it in the patch
