### ISSUE TITLE
Cant Export with GUI and Parameters - Ubuntu 23.04 (using xUbuntu 22.04 version)

### ISSUE THREAD

**Issue by ndr0n** [plugdata-team/plugdata#869]
Hey! 
First of all thanks for the great work this is very exiting software! :)

I'm having an issue where, after i compile my PlugData patch as vst3 and open it in a vst3 host DAW (Supercollider or Ardour) I can't open the PlugData GUI (to make changes to the output of my sound) and I also haven't gotten the parameters working (I have parameters setup on my patch but can't seem to send values  to them from my DAW). I can get sound output but since I can't change the parameters it is always the same.

Any idea what i might be doing wrong or if this is a bug?

Thanks!

Edit: This is my PlugData patch which I am exporting to vst3 through the Compile -> DPF -> vst3 option

![image](https://user-images.githubusercontent.com/58706017/236672244-c7b91842-9efc-4adf-93fd-b225ba2cbf83.png)

**Comment by timothyschoen** [comment]
Hi, the DPF plugin export right now doesn't include a GUI. There is a way to define your own automation parameters that it will use though. @dromer is working on it though!

**Comment by dromer** [comment]
DPF has a kind of "generic UI" export, one we have not integrated with the plugdata toolchain yet because we need to sort out all the dependencies for each platform.

It was never advertised you would get a "plugdata GUI" for the DPF export so please don't assume such things. The exported plugin contains NO puredata or plugdata code at all.

At the moment you will get a headless plugin (just like Airwindows!). Most DAWs will provide a generic GUI for you, but if you want a custom GUI, then you will need to write one yourself.
