### ISSUE TITLE
Standalone app becomes unresponsive when dealing with file system

### ISSUE THREAD

**Issue by pdguy93** [plugdata-team/plugdata#944]
Hi, I am not sure if this issue is just a user error or a true bug, because I'm very surprised I haven't seen any other reports of this.

I am using Plugdata 0.71 on my 2015 Macbook Pro with OS 10.14.6. 

The issue is that, when I use the standalone application, and I deal with the file system (for example trying to save or open a patch, and the Finder-style window is displayed), Plugdata gets into a state of being impossible to interact with. 

To elaborate, the file system window will show up and simultaneously I get an 'alert' sound from my OS.

Then the file system window is visible, but greyed out as if some other window is on top of it (even though there is no other window on top of it). I cannot cancel the operation (e.g. save), and I cannot type a file name into that greyed out window to be able to save my file.

I also cannot click back into the main window. Clicking on either window causes the alert sound from my OS. I cannot even quit in the standard way. It seems the only thing I can do once in this state is force quit.

I really hope you can help me with this issue, as I was hoping to use Plugdata for teaching very soon!

**Comment by timothyschoen** [comment]
I recently became aware of this problem, it should be solved on the develop branch of plugdata. I made a change to plugdata to make our [ofelia](https://github.com/plugdata-team/plugdata-ofelia) implementation work, which was difficult because they both have different methods of handling windows, that caused the problem. I now completely rewrote plugdata-ofelia so that problem should no longer exist.

You can try the latest develop branch by downloading a nighly build from here: https://plugdata.org/download.html

**Comment by pdguy93** [comment]
I just installed the older version, 0.70, and this version had no problem as described above; I am able to save and open pd files with the standalone app.

I should also note that when I used the newest (0.71) plugin version (AU opened in Logic Pro X), I was able to save/interact with the file system.

**Comment by timothyschoen** [comment]
This should be fixed in v0.8.0 :)
