### ISSUE TITLE
mrpeach external does not install

### ISSUE THREAD

**Issue by jsr606** [plugdata-team/plugdata#966]
when finding the mrpeach external and clicking install, the file looks like it downloads and installs. it gets a mention in the .pkginfo file in the Deken folder. but there is no actual files in Deken.
i am running popOS. this is my first issue report. hope this is enough information?

**Comment by timothyschoen** [comment]
I think I've seen this happen on Linux before... I'll check this out soon!

**Comment by porres** [comment]
what do you need from it?

**Comment by timothyschoen** [comment]
Unfortunately the mrpeach externals was uploaded as the wrong format, instead of using the standard .dek format (which is really just zip), it's compressed as .tar.gz. It is the only package on Deken that does this, so it's not really our fault. If you want to install this external, it's better to download/install it manually.

**Comment by porres** [comment]
let me insist that ELSE has alternatives for mrpeach externals... depending on what you need
